name: Test Automazione

on: [push]

jobs:
  verifica-progetto:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice del progetto
        uses: actions/checkout@v4

      - name: Verifica esistenza file fondamentale
        run: |
          if [ -f docker-compose.yml ]; then
            echo "File docker-compose.yml trovato! ✅"
          else
            echo "Errore: docker-compose.yml non trovato! ❌"
            exit 1
          fi