name: Test Automazione

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Login su Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MY_DOCKER_USER }}
          password: ${{ secrets.MY_DOCKER_PASS }}

      - name: Build dell'immagine
        run: docker build . -t ${{ secrets.MY_DOCKER_USER }}/mio-progetto:latest

      - name: Push su Docker Hub
        run: docker push ${{ secrets.MY_DOCKER_USER }}/mio-progetto:latest