name: Test Automazione

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Testa la Build Docker
        # Questo comando prova a costruire l'immagine senza salvarla (tag --no-cache)
        run: docker build . --file Dockerfile --tag test-image:latest